Repository pyronear/pyro-mlops, pull requests merged in 2023-06, with the labels that each got.

#7 deleting not needed files 🧹
  dataset/__init__.py
  dataset/load_data.py
  dataset/mnist_fashion/image_0.jpg
  dataset/mnist_fashion/image_1.jpg
  dataset/mnist_fashion/image_2.jpg
  dataset/mnist_fashion/image_3.jpg
  dataset/mnist_fashion/image_4.jpg
  dataset/mnist_fashion/image_5.jpg
  dataset/mnist_fashion/image_6.jpg
  dataset/mnist_fashion/image_7.jpg
  dataset/mnist_fashion/image_8.jpg
  dataset/mnist_fashion/image_9.jpg
  dataset/mnist_fashion_random.py
  model/__init__.py
  model/mlruns/models/model-elasticnet/meta.yaml
  model/mlruns/models/model-pytorch-mnist/meta.yaml
  model/mlruns/models/model-pytorch-mnist/version-1/meta.yaml
  model/model_elasticnet_wine.py
  model/model_yolo_mnist_pretrained.py
  model/runs/detect/exp/zidane.jpg
  model/runs/detect/exp2/zidane.jpg
  model/runs/detect/exp3/zidane.jpg
  model/runs/detect/exp4/image_0.jpg
  model/runs/detect/exp4/image_1.jpg
  model/runs/detect/exp4/image_2.jpg
  model/runs/detect/exp4/image_3.jpg
  model/runs/detect/exp4/image_4.jpg
  model/runs/detect/exp4/image_5.jpg
  model/runs/detect/exp4/image_6.jpg
  model/runs/detect/exp4/image_7.jpg
  model/runs/detect/exp4/image_8.jpg
  model/runs/detect/exp4/image_9.jpg
  runs/runs.csv
Labels: invalid

#10 Setup repo
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/style.yml
  .gitignore
  Makefile
  model/model_pytorch_lightning_mnist.py
  pyproject.toml
  requirements.txt
Labels: type: code quality, type: enhancement

#11 add yolo train example
  .gitignore
  README.md
  model/yolo/requirements.txt
  model/yolo/yolo_config.yaml
Labels: type: enhancement
